### ISSUE TITLE
Cannot import __init__.py'

### ISSUE THREAD

**Issue by Rkkss** [biegert/ComfyUI-CLIPSeg#3]
```
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

Cannot import D:\Stable_difussion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
```

**Comment by ltdrdata** [comment]
> ```
>   File "<frozen importlib._bootstrap_external>", line 1073, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
> 
> Cannot import D:\Stable_difussion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
> ```

You should not git clone. Just save single file into custom_nodes dir.

**Comment by DarkAlchy** [comment]
> > ```
> >   File "<frozen importlib._bootstrap_external>", line 1073, in get_data
> > FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
> > 
> > Cannot import D:\Stable_difussion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\Stable_difussion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
> > ```
> 
> You should not git clone. Just save single file into custom_nodes dir.

![image](https://github.com/biegert/ComfyUI-CLIPSeg/assets/10561690/f409a678-3e59-4fb2-94f6-1d443db4d02e)

Didn't work that other way either.

**Comment by Rkkss** [comment]
instruction was unclear I guess.
